enableScripts: false

packageExtensions:
  "@mdx-js/loader@*":
    dependencies:
      react: "17.0.2"
  "@storybook/addon-docs@*":
    dependencies:
      webpack: "*"
  "@storybook/addon-interactions@*":
    dependencies:
      core-js: "*"
  "@storybook/instrumenter@*":
    dependencies:
      core-js: "*"
      react: "17.0.2"
      react-dom: "17.0.2"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
