enableScripts: false

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/docs-tools@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/instrumenter@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/mdx1-csf@*":
    dependencies:
      "@babel/core": "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
