name: Continuous Integration
description: Runs linting, code coverage, and build
runs:
  using: "composite"
  steps:
    - run: npm install
      shell: bash
    - run: npm run test
      shell: bash
    - run: npm run build
      shell: bash