name: Continuous Integration
description: Runs linting, code coverage, and build
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: npm run lint
      shell: bash
    - run: npm test -- --ci --coverage
      shell: bash
    - run: npm run codecov
      shell: bash
    - run: npm run build
      shell: bash