on:
  workflow_call:
    secrets:
      CHROMATIC_PROJECT_TOKEN:
        required: true

jobs:
  lint:
    name: "Lint Sources"
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - run: yarn install
        shell: bash
      - run: yarn flow-typed-install
        shell: bash
      - run: pipx install poetry
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: poetry
      - run: poetry install
        shell: bash
      # run linting
      - run: yarn flow
        shell: bash
      - run: yarn lint
        shell: bash
  test:
    name: "Test Project"
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - run: pipx install poetry
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: poetry
      - run: poetry install
        shell: bash
      # run tests
      - run: yarn test:js --coverage
        shell: bash
      - run: yarn test:py --cov --cov-report=xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_${{ github.sha }}
          path: ./coverage
          if-no-files-found: error
          retention-days: 1
  coverage:
    name: "Report Coverage"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: coverage_${{ github.sha }}
      - uses: codecov/codecov-action@v3
  chromatic:
    name: "Run Visual Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: bundles_${{ github.sha }}
          path: storybook-static
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static

